name: Check Suite - Completed

on:
  workflow_dispatch: 
  check_suite:
    types:
      - completed

jobs:
  check-suite-completed:
    name: Check Suite - Completed

    runs-on: ubuntu-latest

    steps:
      - name: Log Context
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))
