name: Check Suite - Completed

on:
  check_suite:
    types: [completed]

jobs:
  check-suite-completed:
    name: Check Suite - Completed

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log Context
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context))
